# use these constants to update the naming scheme in the blog posts frontmatter
BLOG_SKIP_KEY = "blog-skip"
BLOG_PUBLISHED_KEY = "blog-published"
BLOG_DATE_KEY = "blog-date"
BLOG_DEMO_VALUE = "demo"
BLOG_ARCHIVED_KEY = "blog-archived"
BLOG_TAGS_KEY = "blog-tags"
BLOG_TITLE_KEY = "blog-title"
BLOG_SUBTITLE_KEY = "blog-subtitle"
BLOG_AUTHOR_KEY = "blog-author"
